TOTAL_NR_OF_PUBLICATIONS = 20
TOTAL_NR_OF_STATIONS = 4

MAXIMUM_TEMPERATURE = 45
MINIMUM_TEMPERATURE = -45

MINIMUM_WIND_SPEED = 0
MAXIMUM_WIND_SPEED = 200

CITIES = ['ROMAN','IASI','CONSTANTA','BRAILA','COSTINESTI','PASCANI','GALATI','BACAU','VASLUI','BLAGESTI']
DIRECTIONS = ['S','SW','SE','NW','NE','N','E','W']


def get_min_len_dataset():
    return min(len(CITIES),len(DIRECTIONS),TOTAL_NR_OF_STATIONS)
